CREATE DATABASE M_OpFlix;

USE M_OpFlix;

CREATE TABLE Formatos (
	IdFormato			TINYINT PRIMARY KEY IDENTITY NOT NULL
	,Formato			VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Categorias (
	IdCategoria		INT PRIMARY KEY IDENTITY NOT NULL
	,Categoria		VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Lancamentos (
	IdLancamento	INT PRIMARY KEY IDENTITY NOT NULL
	,IdCategoria	INT	FOREIGN KEY REFERENCES Categorias (IdCategoria)
	,Titulo			VARCHAR (255) UNIQUE NOT NULL
	,Sinopse		TEXT NOT NULL
	,TempoDuracao	INT	NOT NULL
	,IdFormato		TINYINT	FOREIGN KEY REFERENCES Formatos (IdFormato)
	,IdVeiculos		INT FOREIGN KEY REFERENCES Veiculos (IdVeiculo)
	,DataLancamento	DATE NOT NULL
);

CREATE TABLE Usuarios (
	IdUsuario		INT PRIMARY KEY IDENTITY NOT NULL
	,Nome			VARCHAR (255) NOT NULL
	,Email			VARCHAR (255) UNIQUE NOT NULL
	,Senha			VARCHAR (255) NOT NULL
	,CPF			BIGINT	UNIQUE NOT NULL
	,DataEntrada	DATETIME NOT NULL DEFAULT GETDATE()
	,Permissao		VARCHAR (255) NOT NULL
);

CREATE TABLE Veiculos (
	IdVeiculo		INT PRIMARY KEY IDENTITY NOT NULL
	,Veiculo		VARCHAR (255) UNIQUE NOT NULL
);




