CREATE DATABASE M_OpFlix;

USE M_OpFlix;

CREATE TABLE Tipos (
	IdTipo			TINYINT PRIMARY KEY IDENTITY NOT NULL
	,Tipo			VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Categorias (
	IdCategoria		INT PRIMARY KEY IDENTITY NOT NULL
	,Categoria		VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Lancamentos (
	IdLancamento	INT PRIMARY KEY IDENTITY NOT NULL
	,IdCategoria	INT	FOREIGN KEY REFERENCES Categorias (IdCategoria)
	,Titulo			VARCHAR (255) UNIQUE NOT NULL
	,Sinopse		TEXT NOT NULL
	,TempoDuracao	INT	NOT NULL
	,IdTipo			TINYINT	FOREIGN KEY REFERENCES Tipos (IdTipo)
	,DataLancamento	DATE NOT NULL
);

CREATE TABLE Permissoes (
	IdPermissao		TINYINT PRIMARY KEY IDENTITY NOT NULL
	,Permissao		VARCHAR (255)
);

CREATE TABLE Usuarios (
	IdUsuario		INT PRIMARY KEY IDENTITY NOT NULL
	,Nome			VARCHAR (255) NOT NULL
	,Email			VARCHAR (255) UNIQUE NOT NULL
	,Senha			VARCHAR (255) NOT NULL
	,CPF			BIGINT	UNIQUE NOT NULL
	,IdPermissao	TINYINT	FOREIGN KEY REFERENCES Permissoes (IdPermissao)
	,DataEntrada	DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Favoritos (
	IdUsuario		INT FOREIGN KEY REFERENCES Usuarios (IdUsuario)
	,IdLancamento	INT FOREIGN KEY REFERENCES Lancamentos (IdLancamento)
);
